/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientechat;

import com.google.gson.Gson;
import java.io.PrintStream;
import java.net.Socket;
import java.util.Date;

/**
 *
 * @author lrey
 */
public class Conversacion extends javax.swing.JFrame {

    private final Socket cliente;
    private final String usuario;

    public Conversacion(Socket cliente, String usuario) {
        initComponents();
        this.cliente = cliente;
        new HiloConversacion(cliente, txtConversacion).start();
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtConversacion = new javax.swing.JTextArea();
        txtMensaje = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtConversacion.setColumns(20);
        txtConversacion.setRows(5);
        jScrollPane1.setViewportView(txtConversacion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 590, 310);
        getContentPane().add(txtMensaje);
        txtMensaje.setBounds(20, 340, 490, 24);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar);
        btnEnviar.setBounds(520, 335, 90, 32);

        setSize(new java.awt.Dimension(642, 411));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        try {
            MensajeDTO mensaje = new MensajeDTO();
            mensaje.setUsuario(usuario);
            mensaje.setMensaje(txtMensaje.getText());
            mensaje.setFecha(new Date().getTime() + "");
            PrintStream escribir = new PrintStream(cliente.getOutputStream());
            escribir.println(new Gson().toJson(mensaje));
            escribir.flush();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEnviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtConversacion;
    private javax.swing.JTextField txtMensaje;
    // End of variables declaration//GEN-END:variables
}
